### ISSUE TITLE
Extending the "safe to preview" label to vendor-exported PRs

### ISSUE THREAD

**Issue by domfarolino** [web-platform-tests/wpt.live#28]
Recently I've been reviewing a lot of new lazy loading WPTs coming from both vendors and Googlers, and a lot of times, Chromium committers push WPTs up via Gerrit. In that case it would be useful to extend the functionality of the "safe to preview" PR label to generate previews for these types of PRs, as I often need to test them locally to submit a thorough review. From talking with @stephenmcgruer, it sounds like it'd be possible to create another label similar to "safe to preview" for vendor-generated PRs, but I'm wondering if we could also just extend the functionality of "safe to preview" to work for these PRs as well..I think the less labels the better :)

**Comment by stephenmcgruer** [comment]
Seems like a very reasonable request, and I agree that we should just extend the existing label.

Given that the label hasn't really been used yet, we do have a chance here to rename it if we can think of a better name. I'll start working on the behavior change; feel free to chime in with name suggestions (hardest problem in computer science...) :D

**Comment by stephenmcgruer** [comment]
Note that we are re-using the "safe to preview" label, because we couldn't think of a better name :)
