### ISSUE TITLE
WPT preview bot: Edit main comment to publicize a preview

### ISSUE THREAD

**Issue by domfarolino** [web-platform-tests/wpt.live#29]
(From talking with @stephenmcgruer)

Currently the pr-preview bot edits WHATWG PRs to include, at the bottom of the first comment, a link to a preview of the changes made to a spec, and the diffs. For example, see the first comment of https://github.com/whatwg/html/pull/5302.

I think it'd be really useful, and could increase engagement of the wptpr preview functionality, if something similar could be done for WPT PRs that are safe to have a preview generated. Specifically, if the bot could have links pointing to the effected tests, that would be even more useful. Does this seem reasonable?

**Comment by stephenmcgruer** [comment]
wptpr.live is unfortunately being turned down (https://github.com/web-platform-tests/rfcs/pull/76), so this issue is no longer relevant
