### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.live#40]
Judging by the response to [file-submission.py](https://www1.wpt.live/html/semantics/forms/form-submission-0/resources/file-submission.py) while running [submit-file.sub.html](https://wpt.live/html/semantics/forms/form-submission-0/submit-file.sub.html), the wpt.live server is still using Python 2:
```html
<script>parent.postMessage("FieldStorage('testinput', 'name', 'foobar')", '*');</script>
```

I say that because of what https://github.com/web-platform-tests/wpt/blob/fdccca21ec6beab45bee9eb7c02e33ccabe295ba/html/semantics/forms/form-submission-0/resources/file-submission.py looks like and that when I run `./wpt serve` with Python 3 myself, I get an error in this handler.

@stephenmcgruer has anything been done with wpt.live in terms of py2/3 recently? Looking at the Dockerfiles it seems to me it should already be on Python 3, but I'm not too sure...

**Comment by stephenmcgruer** [comment]
It runs `./wpt serve --config ../wpt-config.json; kill -SIGQUIT $PPID'` (https://github.com/web-platform-tests/wpt.live/blob/master/src/supervisord.conf#L35), which I believe has a `python3` shebang line, so I'm not sure why it wouldn't be running WPT under Py3.

But I've never verified.

**Comment by foolip** [comment]
I think I got myself confused here. I was trying some things out with `curl` against `./wpt serve` and got an error which I took to mean the types were all wrong. But it was because I wasn't sending multipart form data using `curl`. The problem doesn't happen when running the tests and the posted data is on the expected format.

So I would bet that wpt.live is actually on Python 3 already :)
